#name: "book-store-application"
#
#services:
#  catalog-db:
#    image: postgres:17-alpine
#    container_name: catalog-db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "15432:5432"
#    volumes:
#      - book-store-ms:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
##    deploy:
##      resources:
##        limits:
##          memory: 500m
#
#  orders-db:
#    image: postgres:17-alpine
#    container_name: orders-db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "25432:5432"
#    volumes:
#      - book-store-ms:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
##    deploy:
##      resources:
##        limits:
##          memory: 500m
#
#
#  bookstore-rabbitmq:
#    image: rabbitmq:4.0.5-management
#    container_name: bookstore-rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - book-store-ms:/var/lib/rabbitmq
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 30s
#      timeout: 30s
#      retries: 10
##    deploy:
##      resources:
##        limits:
##          memory: 500m
#
#
##  catalog-service:
##    image: maxiflexy/bookstore-catalog-service
##    container_name: catalog-service
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
##      - DB_USERNAME=postgres
##      - DB_PASSWORD=postgres
##    ports:
##      - "8081:8081"
##    restart: unless-stopped
##    depends_on:
##      catalog-db:
##        condition: service_healthy
##    volumes:
##      - book-store-ms:/var/lib/postgresql/data
##    deploy:
##      resources:
##        limits:
##          memory: 700m
#
#  order-service:
#    image: maxiflexy/bookstore-order-service
#    container_name: order-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - ORDERS_CATALOG_SERVICE_URL=http://catalog-service:8081
#      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
#      - DB_USERNAME=postgres
#      - DB_PASSWORD=postgres
#      - RABBITMQ_HOST=bookstore-rabbitmq
#      - RABBITMQ_PORT=5672
#      - RABBITMQ_USERNAME=guest
#      - RABBITMQ_PASSWORD=guest
#      - OAUTH2_SERVER_URL=http://keycloak:9191
#      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
#      - MANAGEMENT_TRACING_ENABLED=true
#      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
#    ports:
#      - "8082:8082"
#    volumes:
#      - book-store-ms:/var/lib/postgresql/data
#    restart: unless-stopped
#    depends_on:
#      orders-db:
#        condition: service_healthy
#      bookstore-rabbitmq:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#
#
#
#volumes:
#  book-store-ms: